### ISSUE TITLE
Issue in posenet.PoseEstimator.

### ISSUE THREAD

**Issue by Dimple-sethi** [matlab-deep-learning/Human-Pose-Estimation-with-Deep-Learning#1] opened 2020-12-25 08:47 UTC
detector=posenet.PoseEstimator;
while running this , getting an error message , unable to resolve the name posenet.PoseEstimator.
all the  toolboxes are properly installed , still facing this issue , please help me out , in urgent need.

**Comment by tohruk** [comment] 2021-01-04 00:25
Hi @Dimple-sethi ,
Thanks for reporting the issue. I was able to reproduce the issue on my MATLAB R2020b. `posenet.PoseEstimator` can be found as below, but `simplePoseNet.mat` cannot be read because `data` folder is not added to the path.
```
>> which posenet.PoseEstimator
C:\Users\username\AppData\Roaming\MathWorks\MATLAB Add-Ons\Toolboxes\Human Pose Estimation with Deep Learning\+posenet\PoseEstimator.m  % posenet.PoseEstimator constructor

>> detector = posenet.PoseEstimator;

Error using load
Unable to read file 'simplePoseNet.mat'. No such file or directory.
Error in posenet.PoseEstimator (line 29)
            d = load(options.MATFile); 
```

I will fix the issue soon. In the meanwhile, can you try to add the `data` folder to your path as a workaround?
```
>> addpath('C:\Users\username\AppData\Roaming\MathWorks\MATLAB Add-Ons\Toolboxes\Human Pose Estimation with Deep Learning\data');
```
Please note that the location of the root folder of the add-on might be different from above.

**Comment by tohruk** [comment] 2021-01-04 01:04
@Dimple-sethi, I have uploaded [the toolbox v1.0.3](https://github.com/matlab-deep-learning/Human-Pose-Estimation-with-Deep-Learning/releases/tag/v1.0.3). Can you try this out?

**Comment by Dimple-sethi** [comment] 2021-01-04 07:13
OK sir,  thank you for your reply, I fixed the error by downloading
toolbox.  Thank you.

**Comment by tohruk** [comment] 2021-01-04 07:30
Thank you for confirming. Closing this issue.

**Closed as completed by tohruk** 2021-01-04 07:30 UTC
